### ISSUE TITLE
DimThread会与数据包冲突导致崩溃

### ISSUE THREAD

**Issue by MaxwellYe0815** [MCTown/MCTS#2]
我的MCTS服务端发生了崩溃，在日志中发现是由DimThread引起的
之后我在在Dimthread的GitHub库中发现了了这个issue： [DimensionalThreading/issues/42](https://github.com/WearBlackAllDay/DimensionalThreading/issues/42)
希望您能在MCTS包中作出一定的提醒
我的崩溃日志
[crash-2022-04-23_00.39.42-server.txt](https://github.com/MCTown/MCTS/files/8546404/crash-2022-04-23_00.39.42-server.txt)

**Comment by yikerman** [comment]
dimthread现有bug较多 不建议使用
