### ISSUE TITLE
作者MCBBS号咋被ban了 还更新吗（）

### ISSUE THREAD

**Issue by fengguowudi** [MCTown/MCTS#6]

**Comment by xiaoyu2006** [comment]
主要的告示牌功能在1.20被麻将加入进原版里了，服务器暂时没需求就没有添加。

@fengguowudi 如果有需求可以开issue提出。

**Comment by Apricityx** [comment]
谢邀，更新是一直持续的，进下载链接就可看到1.20.1的端了

**Comment by yikerman** [comment]
@Apricityx 有时间把Dockerfile连着repo一起更新一下

**Comment by Apricityx** [comment]
> @Apricityx 有时间把Dockerfile连着repo一起更新一下

目前有报告说docker性能损耗较大，故暂时停止更新docker版

**Comment by fengguowudi** [comment]
> 谢邀，更新是一直持续的，进下载链接就可看到1.20.1的端了

抱歉之前没注意 =。= 感谢大佬的勤奋付出。大佬不重开个mcbbs账号吗，我一定火速去顶帖）））

**Comment by Apricityx** [comment]
> > 谢邀，更新是一直持续的，进下载链接就可看到1.20.1的端了
> 
> 抱歉之前没注意 =。= 感谢大佬的勤奋付出。大佬不重开个mcbbs账号吗，我一定火速去顶帖）））

个人对MCBBS的管理机制不满意，所以不打算重新注册账号，以后如果有什么问题欢迎发issue
